### PR TITLE
Temporal hotfix for issue #326

### PR DESCRIPTION
**Pull request by OuroboricCycle**
Just went ahead and added aiohttp(2.3.10) as a requirement

Tested by deploying to heroku from github (using my fork’s other branch “aiohttp-bug-workaround”)

### CODE REVIEW

**Comment by omelody213** [comment]
Fixed my issue (for now.)
Thank you very much.

**Comment by ZackaryH8** [comment]
image - It saying this version is incompatible...

**Comment by ZackaryH8** [comment]
image
It says that version is incompatible...

**Comment by omelody213** [comment]
It says that for me too, Zackary, but it works none-the-less.

**Comment by LyricLy** [comment]
This seems like a flimsy fix over removing the `yarl<1.2` requirement instead, which would keep every version compatible.

**Comment by OuroboricCycle** [comment]
The latest stable aiohttp version is 2.3.10, so in reality it is compatible, it’s just that in the latest discord.py rewrite update(or at least that’s what I’m seeing) somehow the developer made an error by indicating that the (currently) non-existent 3.3.0 to 3.4.0(?) versions of aiohttp were a requirement

The latest _bleeding edge/beta_ release of aiohttp is 3.0.0, so...

**Comment by LyricLy** [comment]
Wrong, aiohttp 2 is in fact *not* the latest stable release of aiohttp. Just do a manual pip install command of it and you can clearly see 3 is the latest version. The problem is that the `yarl<1.2` requirement is indirectly forcing the version to aiohttp 2, which is incompatible with discord.py. The solution is to remove that requirement.

**Pull request closed without merging**
