### PR TITLE
#255 on correct branch

### PR DESCRIPTION
**Pull request by GriffinG1**

### CODE REVIEW

**Comment by GriffinG1** [comment]
Then what name do you suggest? I know @appu1232 wanted a name change, and those two names are the only ones that accurately describe the command

**Comment by LyricLy** [comment]
Since the command will probably not end up being used by many users except for specific cases, it may not be necessary to use a name that clearly describes the purpose of the command.

**Comment by GriffinG1** [comment]
So what? Name it jdskhjfkijhds?

**Comment by GriffinG1** [comment]
**cogslist** could actually work now that i think about it.. a missed space is easier than an accidental **s** instead of the space. Can we agree on that for now?

**Comment by LyricLy** [comment]
How about `clist` or `cinfo`?

**Comment by GriffinG1** [comment]
hmm... how about `loaded` as the main, with `clist` and `cinfo` as aliases?

**Pull request merged**
