### PR TITLE
added debug command

### PR DESCRIPTION
**Pull request by Bluscream**

### CODE REVIEW

**Comment by appu1232** [comment]
Good command, going to save it for later (for dev branch) after the config-manager stuff is fixed. Currently it'll be a huge pain to merge these two branches that are already so far apart. I will save this and properly credit you when we have everything set.

**Comment by Bluscream** [comment]
can't you just leave it open then? :D

**Comment by appu1232** [comment]
Actually, just create the request for the config-manager branch

**Comment by Bluscream** [comment]
sure thing

**Pull request closed without merging**
