### PR TITLE
appuselfbot.py: improve ready message

### PR DESCRIPTION
**Pull request by bmintz**
Why is try-except needed for `bot.user.name` anyway?

### CODE REVIEW

**Comment by bmintz** [comment]
lol it's cause i used tabs

**Comment by appu1232** [comment]
Try except was used because of certain Discord names causing unsupported char errors on certain systems. If anything, use doing something along the lines of `print(message.encode(errors='replace').decode())` to account for this problem.

**Comment by Sugiyo-slamet** [comment]
How to get VPS?

**Comment by chenzw95** [comment]
@Sugiyo-slamet requests for support should go to our Discord server. Do not hijack other threads.

**Comment by architdate** [comment]
Is this ready for merge?

**Comment by chenzw95** [comment]
Nope, I think it's not ready for merge; appu's comment has not been addressed yet.

**Comment by bmintz** [comment]
OK, I think I addressed them.

**Comment by chenzw95** [comment]
Please reconsider appu's suggestion; I am not sure if skipping the printing of the entire username is what we really want here.

**Comment by appu1232** [comment]
Not sure the try catch is necessary, could just do the `print(message.encode(errors='replace').decode())` which would simply be the same as `print(message)` if there are no errors anyway. But w/e i'll merge this.

**Pull request merged**
